name: RaudonisTablist
version: '1.0-SNAPSHOT'
main: de.ritzenbergen.raudonistablist.RaudonisTablist
api-version: '1.21'
authors: [ R40fendt ]
description: Tablist Fake-Player Plugin, um Spieler auf anderen Servern anzuzeigen
